### ISSUE TITLE
2022-03-15 "Hello Everyone" Comments

### ISSUE THREAD

**Issue by BennyQBD** [BennyQBD/thebennyblog#1]
Here's a place where you can leave comments and discussion for the post https://bennyqbd.github.io/thebennyblog/jekyll/update/2022/03/15/hello-everyone!.html

**Comment by agausmann** [comment]
It is great to hear from you again! Your YouTube content was the main reason that I got interested in redstone, digital logic more generally, and computer graphics. And now, almost 10 years later, I'm finally finishing my CS degree with comp eng also in progress, and I'm continuing to use those hobbies with projects like [FlipFlop](https://github.com/agausmann/FlipFlop.git).

Again, thank you! And I cannot wait to see what you've been working on. 😄

**Comment by harrand** [comment]
Great to hear from you again bud, looking forward to what you have planned

**Comment by GeneRickUsername** [comment]
Benny is Back.

**Comment by stickyfingies** [comment]
Welcome back Benny!

**Comment by lukinator1** [comment]
I've got an idea, why not make a video that links to the blog

**Comment by TheWildJarvi** [comment]
Welcome back Benny, Im looking forward to what you have to share <3 
,gg34

**Comment by LordDecapo** [comment]
Welcome back dude!
Hope you have been doing great! 
Just like everyone else, I am looking forward to seeing what is in store!

**Comment by JamJar2004** [comment]
You coming back was the best surprise of the day! Can't wait to see what you have to share!

**Comment by pat-gc** [comment]
cant believe it im so happy

**Comment by GeneRickUsername** [comment]
Yarharhar MAyert.

**Comment by TheRedXD** [comment]
Man thank god you're still out there lmao
You should seriously come back to the channel, some people don't even have a single idea of your existence anymore
My suggestion - make an update video that basically explains your current position. Your current format doesn't seem to be working, so I think you need more interesting videos, perhaps with other people contributing as well? You need to make your videos more fun to watch, not just educational. I feel like that could help you.

Sending love,
Red.

**Comment by KittenMeow** [comment]
I know this is a late comment, but I was surprised (in a good way) to see this blog. 

Stutav

**Comment by CodePenguino** [comment]
Nice!
