### ISSUE TITLE
2022-06-01 "June Progress Update" Comments

### ISSUE THREAD

**Issue by BennyQBD** [BennyQBD/thebennyblog#3]
Here's a place where you can leave comments and discussion for the post https://bennyqbd.github.io/thebennyblog/jekyll/update/2022/06/01/juneupdate.html

**Comment by rdrpenguin04** [comment]
Question: Would you have any interest in doing a Rust-based project down the road?

Glad to see you back, and I know the whole community is too!

**Comment by BennyQBD** [comment]
@rdrpenguin04 I haven't specifically prepared anything Rust-based at this exact moment, but it's something on my list of things to consider. I like a lot about Rust in principle and it could be an especially great tool for exploring some lower level topics like Vulkan. Not that I know for sure that I'd use Rust for Vulkan at this point.

Either way, I think it'd be great to eventually fit Rust in _somewhere_, even if I'm not 100% sure precisely where that would be at the moment.

Also, thanks for the kind wishes. I hope you and the rest of the community are all doing well.

**Comment by rdrpenguin04** [comment]
Thank you, and good luck!
